import { useState } from "react";

const ROOM_DATA = [
   "A faint smell of ozone and burnt sugar.",
  "Walls inscribed with a repeating, silent, screaming face.",
  "A single, glowing, floating eyeball that turns to watch the nearest motion. Explodes into a gooey mess if touched.",
  "Chains hanging from the ceiling, coated in a thick, iridescent slime.",
  "A pool of perfectly still, pitch-black water that reflects nothing.",
  "A pedestal holding a half-eaten, petrified loaf of bread.",
  "Cobwebs thick with iridescent dust that shimmers in faint light.",
  "The air is unnaturally heavy, as if underwater, though dry.",
  "Footprints in the dust that abruptly stop, mid-stride.",
  "A broken hourglass, its sand replaced with tiny, glittering gears.",
  "Carvings of stylized, multi-limbed insects adorning the lintels.",
  "A series of clay pots, each containing a single, perfectly preserved human finger.",
  "A discarded, rusted music box playing a slow unrecognizable tune.",
  "Patches of glowing, blue-veined fungus pulse faintly on the walls.",
  "A faint, high-pitched hum that seems to vibrate in your teeth.",
  "Stone pillars draped with thin, translucent, dried skin-like material.",
  "A single, withered flower, perfectly preserved in a cube of clear amber.",
  "A small, intricate cage made of bone, with its door ajar.",
  "The floor is covered in a layer of fine, black ash that crackles underfoot.",
  "A discarded, single-gloved hand, severed, grasping a rusted key.",
  "A mural depicting figures with reversed heads, staring over their shoulders.",
  "The distant, rhythmic clang of metal on stone, echoing.",
  "A discarded, half-melted wax doll with pins sticking from its chest.",
  "The air smells faintly of old spices and distant rain.",
  "A small, ornate silver bell that, when rung, produces no sound but a feeling of dread.",
  "A pile of brittle, dried leaves that crumble to dust at the slightest touch.",
  "Flickering shadows on the walls that seem to move independently of the light source.",
  "A broken mechanical bird that twitches occasionally, attempting to sing.",
  "A stone slab carved with a complex circuit diagram that glows faintly green.",
  "A pool of shimmering, viscous liquid that moves to avoid being touched.",
  "A wooden table with a single, perfectly round hole burned through its center.",
  "A faint, sweet, cloying smell, like rotten fruit and cheap perfume.",
  "Walls stained with swirling patterns of a deep, unsettling purple.",
  "A collection of small, crudely carved wooden figurines, each missing a limb.",
  "The floor is unusually warm to the touch in patches, then abruptly cold.",
  "A tapestry depicting a landscape where all the trees are growing down from a cloud bank.",
  "A discarded, child-sized shoe filled with small, smooth, polished stones.",
  "The sound of slow, heavy breathing, but no visible source.",
  "Pillars made of twisted, petrified wood, covered in strange, glowing runes.",
  "A small, closed wooden box emitting a faint, rhythmic scratching sound from within. Empty and silent if opened.",
  "A discarded, half-eaten piece of crystalline fruit that gives off a faint hum. If eaten, causes eyes to glow for 1d6 hours",
  "The air shimmers distorting distant objects, as if seen through heat haze.",
  "A broken abacus, its beads replaced with tiny, shriveled eyeballs.",
  "A single, unlit candle on a tall, elegant silver candlestick, smelling of beeswax.",
  "Walls covered in ancient, peeling wallpaper depicting endlessly repeating mazes.",
  "A pile of discarded, mismatched boots, all for the right foot.",
  "The faint scent of stagnant water and mildewed cloth.",
  "A broken mirror reflecting only the sky, regardless of its position.",
  "A pedestal holding a perfectly round, polished black stone, warm to the touch.",
  "A single, unbroken ceramic plate with a painting of a crying clown.",
  "A section of wall covered in child-like drawings of grotesque monsters.",
  "The floor is sticky with dried honey.",
  "A large, empty fish tank, filled with intricate, dried-out coral.",
  "A faint, intermittent buzzing sound, as if from trapped insects.",
  "A pile of rusted tools, some unrecognizable, forming a cairn.",
  "The air is thick with shimmering pollen, causing a mild cough.",
  "A half-built stone archway, seemingly leading to nowhere.",
  "A discarded, singed parchment, with faint, burnt symbols still visible.",
  "A puddle of perfectly clear water that refracts light in impossible ways.",
  "Walls covered in scratch marks, as if something large was trying to escape.",
  "A small, wooden toy boat, half-sunk in a puddle of stagnant water.",
  "The air smells faintly of old paper and something vaguely fungal.",
  "Dirt floor carpeted with moss except for a circle of scorched earth, with nothing growing within it.",
  "A heavy iron cube, perfectly smooth, hangs from a chain. A faint voice from inside says \"Let me out.\" Nothing but cold air can be found inside.",
  "The sound of something scurrying just out of sight, never quite seen.",
  "A broken cage of woven vines, containing remnants of small bones.",
  "A small, ornate, brass key, glowing with a faint, internal light. A keyhole in a wall can be found by careful searching. It opens a small compartment with a pouch of golden snake scales.",
  "The floor is covered in a uniform layer of fine, red sand.",
  "A mosaic mural of constellations that don't match any known sky.",
  "A discarded, empty glass vial, still smelling faintly of sulfur.",
  "The air is dry and tastes faintly of tumeric.",
  "A series of stone shelves, each holding a different variety of petrified fungi.",
  "A large, wooden wheel, embedded in the wall, slowly turning without apparent power.",
  "Faint whispers that seem to come from inside the walls themselves.",
  "A small, crudely painted picture of a smiling cat on a stone wall.",
  "A low, distant thrumming that vibrates through the floor.",
  "A pile of broken ceramic shards, reflecting dull, colored light.",
  "The scent of decaying flowers and stale water.",
  "A single, large, marble spider, perfectly still, mounted on the wall.",
  "A discarded, empty birdcage, its bars twisted outward.",
  "Walls covered in an impossibly intricate web of glowing, thin wires.",
  "The sound of faint, ghostly music, like a broken harpsichord.",
  "A stone statue of a hooded figure, its hands outstretched, holding nothing.",
  "A pool of dark, swirling liquid that occasionally produces flashes of light. 2d6 goldfish swim in it.",
  "A pile of discarded, empty, glass jars, some with unidentifiable pink residue.",
  "The air is noticeably colder in a specific spot, even if the surrounding area is warm.",
  "A faded mural of a monstrous, many-eyed fish swimming through stars.",
  "A single, perfectly round, unlit brazier, emitting a faint, cold mist.",
  "The floor is covered in a thin, dry layer of what appears to be bone dust.",
  "A rusty, old bucket, perpetually half-filled with clear, dripping water from an unseen source.",
  "A large, unlit lantern, its glass covered in thick, dark fingerprints.",
  "The air carries a faint, sickly sweet scent, reminiscent of rotting fruit.",
  "Walls embedded with countless small, sharp fragments of bone.",
  "A discarded, half-burned book, its pages fused together by heat.",
  "A small pile of discarded, brightly colored insect wings.",
  "The sound of something skittering rapidly across the ceiling. There is only a painting of a large roach.",
  "A single, large, dead plant with glowing, crystal leaves.",
  "A small, ornate, wooden chair, perfectly balanced on one leg.",
  "The walls are unnaturally smooth, almost slick to the touch, despite being stone.",
  "A discarded, rusted tin can, humming faintly with an internal vibration.",
  "A faint, high-pitched hum that seems to come from everywhere and nowhere, causing a subtle pressure behind the ears.",
  "The air shimmers faintly, causing minor visual distortions that make distant objects appear wavy.",
  "A pervasive scent of petrichor, as if rain just fell, but everything remains dry.",
  "Gentle, unseen breezes that whisper faint, unintelligible words that just evade comprehension.",
  "Small, iridescent motes of light drift lazily through the air, flickering out if disturbed.",
  "The faint scent of ozone, hinting at recent electrical discharge or a powerful, contained energy source.",
  "A palpable stillness, where even echoes seem to die prematurely, creating a sense of isolation.",
  "Sporadic, distant chimes, like glass breaking, no visible source or resulting debris.",
  "A low, resonant thrumming that vibrates through the floor, causing small, loose objects to subtly shift.",
  "The air carries a metallic tang, like old blood or rusted iron, growing stronger near certain spots.",
  "Shadows seem to deepen and stretch unnaturally, contorting familiar shapes into unsettling forms.",
  "A subtle, sweet aroma, like decaying fruit, hangs heavy. Hundreds of flies buzz around the room.",
  "Tiny, localized whirlwinds of dust that appear and vanish spontaneously, leaving no trace.",
  "The air crackles with static electricity, causing hair to stand on end and small sparks to jump between metal objects.",
  "Faint, rhythmic dripping sounds, but no visible source of water.",
  "A sensation of immense pressure, as if the walls are slowly closing in, leading to a feeling of claustrophobia.",
  "The faint, sweet smell of burnt sugar, which intensifies then quickly fades.",
  "A chilling cold that seems to seep into the bones, but the ambient temperature remains surprisingly mild.",
  "Shifting patterns of light and shadow on the walls, as if from an unseen, moving source or an active illusion.",
  "A feeling of profound sorrow that blankets the area, affecting those sensitive to emotions with a melancholic weight.",
  "Vibrant blue fungi that pulse with a soft bioluminescence, drawing flies and moths into their glowing caps.",
  "Spanning the floor are thick, gnarled roots that seem to writhe and shift slightly when unobserved, like sleeping serpents.",
  "Clusters of black, obsidian-like flowers that absorb all ambient light, creating small pockets of unnatural darkness.",
  "Spindly, whip-like vines that retract sharply if brushed against, leaving a faint stinging sensation.",
  "Puffball mushrooms that release clouds of fine, shimmering spores when disturbed, causing temporary itchiness.",
  "Crystal-leafed bushes that chime softly when a breeze passes through them, producing an ethereal melody.",
  "Carnivorous pitcher plants, large enough to trap small creatures, filled with iridescent, slightly viscous fluid.",
  "Root systems that have grown into intricate, unsettling patterns on the cavern floor, resembling skeletal hands.",
  "Glow-in-the-dark lichens that paint the walls with shifting, ephemeral murals, responding to nearby movement.",
  "Small potted trees with bark that resembles flaking human skin, weeping a clear, slightly viscous sap.",
  "Suspended air plants with long, hair-like tendrils that sway without a breeze, as if breathing.",
  "Thorn-covered shrubs that slowly bleed a viscous, green liquid when touched, which has a mild sedative effect.",
  "Giant, bell-shaped flowers that emit a deep, resonating hum when approached, causing a slight vibration in the chest.",
  "Vines that have grown into the shape of coiled serpents along the walls, their texture mimicking scales.",
  "Moss that changes color based on who is looking at it, shifting through the spectrum as one's gaze moves.",
  "Fungus that mimics the sound of voices, often repeating phrases heard hours before.",
  "Pale, translucent fungi that resemble human hands, clutching at the air from the walls and ceiling.",
  "Shrubs bearing small, perfectly spherical fruit that taste like pure despair, inducing a fleeting sadness.",
  "Trees with branches that twist into gallows-like shapes, with phantom ropes swaying gently.",
  "Flowers that release a sleep-inducing pollen when agitated.",
  "Root systems that have grown around and through three ancient skeletons, incorporating them into the living plant structure.",
  "Luminescent algae that glow brighter in response to sound, flaring with each spoken word.",
  "Creeping vines that slowly but visibly expand their reach by inches per minute, audibly scraping stone.",
  "Mushrooms that deflate with a soft sigh when touched, releasing a puff of odorless air.",
  "Plants with leaves that are unnaturally cold to the touch, leaving patches of frost on surfaces.",
  "Fungi that mimic the appearance of discarded treasures, like gold coins or jewels, only to crumble to dust when handled.",
  "Trees with hollow trunks that resonate with faint, mournful whispers, like trapped spirits.",
  "Sprawling root networks that form natural, uncomfortable chairs and benches, seeming to invite rest.",
  "Flowers that bloom only in absolute darkness, wilting instantly if exposed to any light source.",
  "Moss that, when stepped on, briefly emits a faint, human-like scream before falling silent again.",
  "A large, circular stone table, its surface covered in strange, interlocking grooves.",
  "A collection of chairs made from intricately carved, petrified wood, depicting unsettlingly lifelike bugs and small animals.",
  "Bunks constructed from rusted iron bars and tattered, mildewed canvas, still faintly smelling of human sweat.",
  "A desk fashioned from a single, polished slab of dark, unidentifiable stone, cold to the touch even in warm air.",
  "Shelves overflowing with strangely shaped, unbaked clay pots and figurines, some resembling grotesque faces.",
  "A throne made of interlocking gears and cogs, softly whirring and grinding.",
  "A shattered wooden cabinet, its drawers hanging open, spilling dust that glows faintly.",
  "An ornate, four-poster bed draped with heavy, cobweb-laden velvet, exuding a scent of ancient perfume.",
  "A large, cracked mirror set into a dressing table adorned with faded cosmetics, reflecting distorted images.",
  "A broken grand piano, its keys yellowed and many missing, occasionally playing a single, haunting note on its own.",
  "A stack of dusty, empty crates, some bearing faded, unreadable labels, suggesting unknown contents from long ago.",
  "A workbench littered with rusted tools and strange, half-finished clockwork devices, still faintly ticking.",
  "A set of crudely assembled stone benches arranged in a haphazard circle.",
  "A tall, narrow wardrobe filled with tattered, moth-eaten robes.",
  "A long, communal dining table made of rough-hewn timber, stained with ancient, dark spills.",
  "A leaning bookshelf packed tightly with scrolls bound in dry, brittle leather, each scroll feeling strangely warm.",
  "A low, wide ottoman made from stretched, flayed hide, still unnervingly supple to the touch.",
  "A broken loom, still strung with threads of an unknown, shimmering material, that subtly changes color.",
  "A small, intricately carved wooden chest, its lock corroded shut, but emitting faint sounds from within.",
  "A collection of overturned, splintered chairs around a burnt-out fireplace, the air around them unnaturally cold.",
  "A strange, multi-tiered pedestal, each tier empty except for dust.",
  "A set of stone-carved cots, each with a hollow where a head would rest, smooth and cold from countless past occupants.",
  "A large, spherical cage, seemingly designed for a creature, its bars bent outwards from immense force.",
  "A broken sundial, its gnomon snapped, lying on a stone plinth, its surface scarred by ancient, unidentifiable symbols.",
  "A large, wooden chest bound with iron bands, too heavy to easily move, half-buried in dust, radiating faint heat.",
  "Murals depicting grotesque, multi-limbed figures engaged in a silent dance, their expressions shifting subtly as you pass.",
  "Statues of elongated, emaciated figures with hands clasped in eternal prayer, their eyes appearing to weep real, dark tears.",
  "A series of tapestries woven with metallic threads, depicting a sky full of alien stars, some constellations unnervingly familiar.",
  "Paintings rendered in thick, clotted paint, showing abstract forms that seem to shift and reconfigure as you observe them.",
  "A collection of masks carved from bone, each with a single, large eye, that seems to blink slowly when unwatched.",
  "Sculptures of intertwined creatures, half-beast, half-plant, their surfaces feeling oddly soft to the touch.",
  "Faded frescoes on the ceiling depicting a grand, but forgotten, cityscape, whose buildings occasionally shimmer as if real.",
  "A gallery of distorted portraits where the subjects' eyes follow you, and their smiles widen unnaturally as you move closer.",
  "Abstract geometric patterns carved into the floor, subtly glowing and pulsating with a soft, internal light.",
  "Ornate iron gates, depicting scenes of torture or celestial judgment, that emit faint, pained whispers when touched.",
  "Large, cracked ceramic pots painted with intricate, repeating symbols, which glow faintly when a person with magic is near.",
  "A mural showing a single, colossal eye gazing out from a swirling void, from which a faint breeze seems to emanate.",
  "Statues of figures with featureless faces, draped in real, decaying cloth, the fabric feeling like ancient, dry skin.",
  "Paintings depicting impossible architecture and gravity-defying structures, which can cause a sense of disorientation.",
  "A series of small, unsettling dolls made from dried plant matter and human hair, each one clutching a tiny, unidentifiable shard.",
  "Carvings on the walls that seem to be whispering if you press your ear to them, the words just beyond understanding.",
  "Stained-glass windows depicting fragmented scenes of a catastrophic event, the glass vibrating with unseen energy.",
  "An abstract sculpture made of polished, black metal that emits a faint chill, drawing the warmth from the air around it.",
  "Paintings of children with eyes that are too old and knowing, their gaze instilling a subtle, lingering unease.",
  "Mosaics of celestial bodies arranged in an unfamiliar pattern, some of which gently pulsate with faint light.",
  "Statues of creatures frozen mid-transformation, half-flesh, half-stone, their forms eerily lifelike and detailed.",
  "A painting that appears to be entirely black, but reveals fleeting, shadowy figures when viewed out of the corner of your eye.",
  "Relief carvings showing scenes of an ancient ritual where the participants have elongated limbs and extra eyes.",
  "A mural that depicts a sprawling tree with faces in its bark, the eyes seeming to follow your movement.",
  "Statues carved from a single block of translucent stone, depicting sleeping figures with peaceful expressions.",
  "A collection of strange glyphs etched into the floor, glowing faintly and pulsing rhythmically.",
  "A small, broken automaton, half-buried in dust, whose single remaining eye blinks once in a while.",
  "A giant coiled serpent sleeps curled about a nest of 2d4 eggs.",
  "2d6 goblins take turns throwing pebbles at a chained manticore.",
  "2d6 bandits lounge about a ragged camp. Two dead bandits lie in a corner.",
  "An ogre in a powdered wig holds a large crude wooden mallet. It calls itself The Judge.",
  "3d6 barrels of pickles. One barrel contains the body of a pickled wizard with a ring of levitation.",
  "2d6 dead goblins with flickering crystal growths bursting from sores on their bodies.",
  "A giant raven skeleton arranged in a natural looking pose. A plaque in a goblin language reads: The queen’s favorite bird. Slain by Hank.",
  "Four humans with crowbars try to pry a large gemstone from a stone wall. They don’t know it holds back a torrent of magma.",
  "d6x20 large sleeping bats hang from iron rings plastered into the ceiling. Troughs and barrels of guano line the floor beneath them.",
  "Stacks of stolen wagon wheels create a maze-like path to a small area where a gnome sleeps in a hammock. Sketches of wheeled contraptions litter the floor.",
  "2d6 troglodytes roast a fat slug over a fire.",
  "2d6 slugs crawl over a pile of human bones, eating any remaining flesh."
];

function getRandomRooms(count = 5, lockedIndices = [], currentRooms = []) {
  const unlockedIndices = Array.from({ length: currentRooms.length }, (_, i) => i).filter(i => !lockedIndices.includes(i));
  const availableRooms = ROOM_DATA.filter(room => !currentRooms.includes(room));
  const shuffled = [...availableRooms].sort(() => 0.5 - Math.random());

  const newRooms = [...currentRooms];
  for (let i = 0, j = 0; i < currentRooms.length && j < shuffled.length; i++) {
    if (!lockedIndices.includes(i)) {
      newRooms[i] = shuffled[j++];
    }
  }

  return newRooms;
}

export default function App() {
  const initialRooms = Array.from({ length: 5 }, () => ROOM_DATA[Math.floor(Math.random() * ROOM_DATA.length)]);
  const [rooms, setRooms] = useState(initialRooms);
  const [locked, setLocked] = useState([]);

  const toggleLock = (index) => {
    setLocked((prev) =>
      prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]
    );
  };

  const generateRooms = () => {
    setRooms((prevRooms) => getRandomRooms(5, locked, prevRooms));
  };

  return (
    <div>
      <h1>Dungeon Rooms</h1>
      <button onClick={generateRooms}>Generate New Rooms</button>
      {rooms.map((room, index) => (
        <div key={index} style={{ border: locked.includes(index) ? '2px solid red' : '1px solid gray', marginBottom: '10px', padding: '10px' }}>
          <p><strong>{index + 1}.</strong> {room}</p>
          <button onClick={() => toggleLock(index)}>{locked.includes(index) ? 'Unlock' : 'Lock'}</button>
        </div>
      ))}
    </div>
  );
}
